
package GUI;

import accesoDatos.BaseDatosRegistro;

/**
 *
 * @author Lenovo
 */
public class JFMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFMenu.class.getName());

    private BaseDatosRegistro bd;

    public JFMenu() {
        bd = new BaseDatosRegistro();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskFondo = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniMozo = new javax.swing.JMenuItem();
        mniMesas = new javax.swing.JMenuItem();
        minPlatos = new javax.swing.JMenuItem();
        mniBebidas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniNuevoPedido = new javax.swing.JMenuItem();
        mniPedidosAct = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniCuentasAbiertas = new javax.swing.JMenuItem();
        mniBucar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniVentasDia = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deskFondo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/restDonSant.png"))); // NOI18N

        deskFondo.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deskFondoLayout = new javax.swing.GroupLayout(deskFondo);
        deskFondo.setLayout(deskFondoLayout);
        deskFondoLayout.setHorizontalGroup(
            deskFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        deskFondoLayout.setVerticalGroup(
            deskFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        jMenu1.setText("Registro");
        jMenu1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N

        mniMozo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        mniMozo.setText("Mozos");
        mniMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMozoActionPerformed(evt);
            }
        });
        jMenu1.add(mniMozo);

        mniMesas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        mniMesas.setText("Mesas");
        mniMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMesasActionPerformed(evt);
            }
        });
        jMenu1.add(mniMesas);

        minPlatos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        minPlatos.setText("Platos");
        minPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minPlatosActionPerformed(evt);
            }
        });
        jMenu1.add(minPlatos);

        mniBebidas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        mniBebidas.setText("Bebidas");
        mniBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBebidasActionPerformed(evt);
            }
        });
        jMenu1.add(mniBebidas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Toma de pedidos");
        jMenu2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N

        mniNuevoPedido.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        mniNuevoPedido.setText("Nuevo pedido");
        mniNuevoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNuevoPedidoActionPerformed(evt);
            }
        });
        jMenu2.add(mniNuevoPedido);

        mniPedidosAct.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        mniPedidosAct.setText("Ver pedidos activos");
        mniPedidosAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPedidosActActionPerformed(evt);
            }
        });
        jMenu2.add(mniPedidosAct);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cuentas");
        jMenu3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N

        mniCuentasAbiertas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        mniCuentasAbiertas.setText("Cuentas abiertas");
        mniCuentasAbiertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCuentasAbiertasActionPerformed(evt);
            }
        });
        jMenu3.add(mniCuentasAbiertas);

        mniBucar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        mniBucar.setText("Buscar cuenta");
        mniBucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBucarActionPerformed(evt);
            }
        });
        jMenu3.add(mniBucar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes");
        jMenu4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N

        mniVentasDia.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        mniVentasDia.setText("Ventas del día");
        mniVentasDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVentasDiaActionPerformed(evt);
            }
        });
        jMenu4.add(mniVentasDia);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        jMenu5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N

        salir.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        salir.setText("Terminar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu5.add(salir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskFondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskFondo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minPlatosActionPerformed
    JIFPlatos jifPlatos = new JIFPlatos(bd); // Crear instancia
    deskFondo.add(jifPlatos);              // Agregar al JDesktopPane
    jifPlatos.setVisible(true);
    }//GEN-LAST:event_minPlatosActionPerformed

    private void mniNuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNuevoPedidoActionPerformed
    JIFNuevoPedido NuevoPedido = new JIFNuevoPedido();
    deskFondo.add(NuevoPedido);
    NuevoPedido.setVisible(true);
    }//GEN-LAST:event_mniNuevoPedidoActionPerformed

    private void mniCuentasAbiertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCuentasAbiertasActionPerformed
    JIFCuentasAbiertas jifCuentas = new JIFCuentasAbiertas();
    deskFondo.add(jifCuentas);
    jifCuentas.setVisible(true);
    }//GEN-LAST:event_mniCuentasAbiertasActionPerformed

    private void mniBucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBucarActionPerformed
    JIFBuscar jifBuscar = new JIFBuscar();
    deskFondo.add(jifBuscar);
    jifBuscar.setVisible(true);
    }//GEN-LAST:event_mniBucarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void mniMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMozoActionPerformed
    JIFMozos jifMozos = new JIFMozos(bd); // Crear instancia
    deskFondo.add(jifMozos);              // Agregar al JDesktopPane
    jifMozos.setVisible(true); 
    }//GEN-LAST:event_mniMozoActionPerformed

    private void mniBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBebidasActionPerformed
    JIFBebidas jifBebidas = new JIFBebidas(bd); // Crear instancia
    deskFondo.add(jifBebidas);              // Agregar al JDesktopPane
    jifBebidas.setVisible(true);
    }//GEN-LAST:event_mniBebidasActionPerformed

    private void mniMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMesasActionPerformed
    JIFMesas jifMesas = new JIFMesas(bd); // Crear instancia
    deskFondo.add(jifMesas);              // Agregar al JDesktopPane
    jifMesas.setVisible(true);
    }//GEN-LAST:event_mniMesasActionPerformed

    private void mniPedidosActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPedidosActActionPerformed
    JIFVerPedidos jifVer = new JIFVerPedidos(); // Crear instancia
    deskFondo.add(jifVer);
    jifVer.setVisible(true);
    }//GEN-LAST:event_mniPedidosActActionPerformed

    private void mniVentasDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVentasDiaActionPerformed
    JIFVentasdelDia jifVentasDia = new JIFVentasdelDia();
    deskFondo.add(jifVentasDia);
    jifVentasDia.setVisible(true);
    }//GEN-LAST:event_mniVentasDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskFondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem minPlatos;
    private javax.swing.JMenuItem mniBebidas;
    private javax.swing.JMenuItem mniBucar;
    private javax.swing.JMenuItem mniCuentasAbiertas;
    private javax.swing.JMenuItem mniMesas;
    private javax.swing.JMenuItem mniMozo;
    private javax.swing.JMenuItem mniNuevoPedido;
    private javax.swing.JMenuItem mniPedidosAct;
    private javax.swing.JMenuItem mniVentasDia;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
